apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/example.conf
          subPath: example.conf
        # - name: shared-files
        #   mountPath: /var/www/html
        - name: my-pvc-local
          mountPath: /var/www/html
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      # - name: shared-files
      #   emptyDir: {}
      - name: my-pvc-local
        persistentVolumeClaim:
          claimName: pvc-local
