apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mysql:8.0
        envFrom:
          - configMapRef:
              name: database-configmap
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: database-pvc
            mountPath: /var/lib/mysql
      volumes:
        - name: database-pvc
          persistentVolumeClaim:
            claimName: database-pvc-do
