apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc-do
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi