apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    # Nginx configuration
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        access_log  /var/log/nginx/access.log  main;
        error_log   /var/log/nginx/error.log;

        root /app;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_pass php-service:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }