apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: leonardomm10/php8.2-fpm-schedulething-api
        ports:
        - containerPort: 9000
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"
            cpu: "0.05"
          limits:
            memory: 500Mi
            cpu: "0.5"
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_ROOT_PASSWORD
                name: database-secret
