apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi